### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [Eblohm/project9#1]
Just a few things I'd like you to update here.

The first is I was able to enter negative numbers for the number fields, which probably isn't desirable in this case. [This Stack Overflow question](http://stackoverflow.com/questions/4416278/how-to-implement-min-max-validator-in-rails-3) should help you resolve that though. Batting average should also have a maximum of 4 too, right?

Then it looks like your navigation style is overreaching a bit to make form errors show up inline instead of in a vertical list.

Also, since RBI is an acronym, labels and table headers where it shows up should probably show `RBIs` instead of `Rbis`. 

Let me know if you have any questions!

**Comment by Eblohm** [comment]
I fixed the issue of the negative numbers! And no, batting average should be between 0 and 1, because it's Hits/At Bats, but I fixed that issue too.

I'm not sure what you mean about the form though? 

And how do I fix that? I've updated the index and show files, but I'm not sure how to fix the issue on the form, where the code is 
    <%= f.label :rbis %>
I don't know how to update that without just removing that line of code and putting RBIs

**Comment by chrisvfritz** [comment]
Ah, I was thinking of how batting averages are calculated in cricket. :stuck_out_tongue: Did you push up those fixes to GitHub? I'm not seeing them yet.

[This Stack Overflow question](http://stackoverflow.com/questions/13003626/custom-text-for-rails-form-for-label) should help you deal with updating the form label.

**Comment by Eblohm** [comment]
Pushed and fixed all the issues! Should be live on github and heroku now.

**Comment by chrisvfritz** [comment]
:+1: Such beauty!
